steps:
  # =========================================================
  # 1. ML SERVICE
  # =========================================================
  # Build ML Service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-ml'
    args: ['build', '-f', 'backend/Dockerfile.ml', '-t', 'gcr.io/$PROJECT_ID/bluebikes-ml', 'backend']
  
  # Push ML Service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-ml'
    args: ['push', 'gcr.io/$PROJECT_ID/bluebikes-ml']
    waitFor: ['build-ml']

  # Deploy ML Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-ml'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bluebikes-ml'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bluebikes-ml'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['push-ml']

  # =========================================================
  # 2. HISTORICAL SERVICE
  # =========================================================
  # Build Historical Service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-hist'
    args: ['build', '-f', 'backend/Dockerfile.historical', '-t', 'gcr.io/$PROJECT_ID/bluebikes-historical', 'backend']
  
  # Push Historical Service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-hist'
    args: ['push', 'gcr.io/$PROJECT_ID/bluebikes-historical']
    waitFor: ['build-hist']

  # Deploy Historical Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-hist'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bluebikes-historical'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bluebikes-historical'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['push-hist']

  # =========================================================
  # 3. NODE BACKEND
  # =========================================================
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-node'
    args: ['build', '-f', 'backend/Dockerfile.node', '-t', 'gcr.io/$PROJECT_ID/bluebikes-backend', 'backend']

  # Push Backend
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-node'
    args: ['push', 'gcr.io/$PROJECT_ID/bluebikes-backend']
    waitFor: ['build-node']

  # Deploy Backend (Needs ML and Historical URLs)
  # Uses a script to discover the URLs of the services deployed in previous steps
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-node'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Retrieving service URLs..."
        ML_URL=$(gcloud run services describe bluebikes-ml --region us-central1 --format 'value(status.url)')
        HIST_URL=$(gcloud run services describe bluebikes-historical --region us-central1 --format 'value(status.url)')
        
        echo "ML_URL: $$ML_URL"
        echo "HIST_URL: $$HIST_URL"
        
        gcloud run deploy bluebikes-backend \
          --image gcr.io/$PROJECT_ID/bluebikes-backend \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars ML_SERVICE_URL=$$ML_URL,HISTORICAL_SERVICE_URL=$$HIST_URL
    waitFor: ['push-node', 'deploy-ml', 'deploy-hist']

  # =========================================================
  # 4. FRONTEND
  # =========================================================
  # Build Frontend
  # Dynamically fetches the backend URL to bake into the React build
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        API_URL=$(gcloud run services describe bluebikes-backend --region us-central1 --format 'value(status.url)')
        echo "Building Frontend with API_URL: $$API_URL"
        
        docker build \
          --build-arg REACT_APP_API_URL=$$API_URL \
          -t gcr.io/$PROJECT_ID/bluebikes-frontend \
          -f frontend/Dockerfile \
          frontend
        
        docker push gcr.io/$PROJECT_ID/bluebikes-frontend
    waitFor: ['deploy-node']

  # Deploy Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bluebikes-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bluebikes-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['build-frontend']

timeout: 1800s
